name: test-token-content-plug
base: core18 
version: '0.1' 
summary: yaga gaga
description: |
  yaga gaga

grade: stable
confinement: strict

plugs:
  # This content interface provides a mechanism for the edgexfoundry
  # snap to shared vault secret tokens in order for services in external
  # edgex snap to access the secret-store. Note, in this case this snap
  # defines a plug instead of slot to allow the consuming snap to create
  # the service-specific directory under $SNAP_DATA/secrets.
  edgex-secretstore-token:
    interface: content
    content: edgex-secretstore-token
    target: $SNAP_DATA/secrets

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: dump
    source: .

